### ISSUE TITLE
Obtaining current position and velocity of robot from gazebo 1.9 using ros hydro

### ISSUE THREAD

**Issue by ktiwari9** [Arn-O/youbot_ros_tools#5]
Hi Arn,
I am using Gazebo with ros hydro and I am spawning a Husky A200 using my launch file only. I want to write a simple node/ edit my urdf somehow so that at any given time Gazebo can tell me my robot position and current velocity. Can I do this using your xacro file from youbot_ros_tools/youbot_description/gazebo/gazebo.urdf.xacro ?
Please advise.

**Comment by Arn-O** [comment]
Hi.

Have a look at the planar plugin:

https://github.com/Arn-O/youbot_ros_tools/blob/master/youbot_description/urdf/youbot.gazebo

I think this is what you are looking for. The odometry is the position.

Keep in mind that it is only possible in a simulator. Otherwise you have to gather the data from sensors.

I hope that helps!

Ar.
